name: Nonfunctional tests

on:
  # will only run when we have finished the deploy to ec2 workflow; before I had a wait till 
  # server is live code (still there; waits 150 s) this just means we can wait longer 
  workflow_run:
    workflows: ["Deploy to EC2"]
    types:
      - completed 
    branches:
      - main

jobs:
  nonfunctional:
    name: Run nonfunctional Python scripts
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      # given we also deploy the server 
      - name: Wait for server to be live
        run: | 
          chmod +x .github/workflows/serverlive.sh
          ./.github/workflows/serverlive.sh

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Run restaurant match script
        run: python testing/nonfunctional/resturantmatch.py

      - name: Run user requirements script
        run: python testing/nonfunctional/userreq.py
